### PR TITLE
[Backend]  Dynamic Default Model Selection Based on Provider Priority

### LINKED ISSUE #522: Default model is hardcoded to claude-4.5 regardless of whether the anthropic key is provided.
### Environment

main

### Steps to Reproduce

as titled.

### Expected Behavior

when anthropic key is not provided, open ai model should take precedence, if no llm key is provided then agent system should be disabled. 

### Actual Behavior

Default model is hardcoded to claude-4.5

### Relevant Logs/Console Output

```shell

```

### Screenshots

_No response_

### Traceroot Version

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by shirleyai-co**
Closes #522

  ## Summary
  Dynamic default model selection based on provider priority instead of hardcoding `claude-sonnet-4-5`.

  ## Type of Change

  - [x] feat - A new feature

  ## Details

  When Anthropic API key is not configured, the AI assistant no longer defaults to an unavailable `claude-sonnet-4-5`. Instead, it dynamically selects the first available model using a configurable priority
  order.

  **Priority order:** Anthropic > OpenAI > DeepSeek > xAI > Moonshot > Z.AI > Google > OpenRouter > Azure > AWS Bedrock

  **Changes across 4 files:**

  - **`frontend/packages/core/src/llm-providers.ts`** — Added `PROVIDER_PRIORITY` constant defining the provider selection order
  - **`frontend/ui/src/features/ai-assistant/components/model-selector.tsx`** — Auto-selects the best available model when current selection is not in the available list (e.g., on first load or when provider
   becomes unavailable)
  - **`frontend/ui/src/features/ai-assistant/components/message-input.tsx`** — Removed hardcoded `claude-sonnet-4-5` default; initial state is now empty, letting ModelSelector auto-pick
  - **`frontend/packages/agent/src/agent.ts`** — New `getDefaultSystemModel()` function checks which system providers have API keys set and picks the first model by priority. Used in both initial and final
  fallback in `resolveModel()`

  **Self-hosting scenario:** If neither Anthropic nor OpenAI is configured but a user has added a Kimi BYOK provider, the model selector will auto-select a Kimi model as the default.

  ## Screenshots / Recordings (if applicable)
  No internal models:
截屏2026-03-21 11 40 39
No internal models and no BYOK models:
截屏2026-03-21 11 41 42
No anthropotic internal model but openAI model:

https://github.com/user-attachments/assets/fea9bf66-403a-4038-920f-bf67aa239757

  ## Checklist

  - [x] I have read the [CONTRIBUTING.md](../CONTRIBUTING.md)
  - [ ] I have added/updated tests where applicable
  - [ ] I have added screenshots or recordings for UI changes (if applicable)
  - [x] I have updated documentation where necessary

### CODE REVIEW

File: frontend/ui/src/features/ai-assistant/components/model-selector.tsx [hunk 1]
```diff
@@ -51,6 +51,28 @@ export function ModelSelector({ value, onChange, workspaceId }: ModelSelectorPro
...
+        const bIdx = PROVIDER_PRIORITY.indexOf(b.provider.toLowerCase());
+        return (aIdx === -1 ? 999 : aIdx) - (bIdx === -1 ? 999 : bIdx);
+      });
+      const best = sorted[0];
+      if (best) {
+        onChange({ model: best.id, provider: best.provider, source: best.source });
+      }
+    }
+    hasAutoSelected.current = true;
+  }, [models, value, onChange]);
```
[the remark this answers is not in the document]
Comment (shirleyai-co) [reply frontend/ui/src/features/ai-assistant/components/model-selector.tsx]: Fixed. Removed the hasAutoSelected ref entirely — the !currentExists check already prevents infinite loops, and now when real API data loads (replacing fallback models), the effect correctly re-evaluates and picks a valid model.

File: frontend/packages/agent/src/agent.ts [hunk 2]
```diff
@@ -205,7 +229,15 @@ function resolveModel(modelId?: string, providerConfig?: ProviderConfig | null)
...
+  // 3. Default — pick best available system model by priority
+  const defaultModel = getDefaultSystemModel();
+  if (defaultModel) {
+    return buildFallbackModel(
+      defaultModel.modelId,
+      defaultModel.apiProtocol,
+      defaultModel.piAIProvider,
+    );
+  }
   return getModel("anthropic", "claude-sonnet-4-5");
```
[the remark this answers is not in the document]
Comment (shirleyai-co) [reply frontend/packages/agent/src/agent.ts:237]: Fixed. getDefaultSystemModel() is now called once and stored in defaultSystemModel, reused in both the initial fallback and step 3.

File: frontend/packages/core/src/llm-providers.ts [hunk 3]
```diff
@@ -112,6 +112,21 @@ export const SYSTEM_MODELS: {
...
+  "openai",
+  "deepseek",
+  "xai",
+  "moonshot",
+  "zai",
+  "google",
+  "openrouter",
+  "azure",
+  "amazon-bedrock",
+];
```
[the remark this answers is not in the document]
Comment (shirleyai-co) [reply frontend/packages/core/src/llm-providers.ts]: Done. Added a comment explaining that the full list is shared between frontend (matches all providers including BYOK) and backend (only matches SYSTEM_MODELS entries, silently skips the rest).

File: frontend/ui/src/features/ai-assistant/components/model-selector.tsx [hunk 4]
```diff
@@ -51,6 +51,28 @@ export function ModelSelector({ value, onChange, workspaceId }: ModelSelectorPro
...
+    if (models.length === 0) return;
+    const currentExists = models.some(
+      (m) => m.id === value.model && m.provider === value.provider && m.source === value.source,
+    );
+    if (!currentExists) {
+      // Pick the first model from the highest-priority provider
+      const sorted = [...models].sort((a, b) => {
+        const aIdx = PROVIDER_PRIORITY.indexOf(a.provider.toLowerCase());
+        const bIdx = PROVIDER_PRIORITY.indexOf(b.provider.toLowerCase());
+        return (aIdx === -1 ? 999 : aIdx) - (bIdx === -1 ? 999 : bIdx);
```
Comment (XinweiHe) [inline frontend/ui/src/features/ai-assistant/components/model-selector.tsx]: This logic here is quite hard to read? any chance we can improve upon this?

File: frontend/packages/core/src/llm-providers.ts [hunk 5]
```diff
@@ -112,6 +112,23 @@ export const SYSTEM_MODELS: {
   },
 ];
 
+// Provider priority for default model selection (highest first).
+// Used by both the frontend ModelSelector (matches all providers including BYOK)
+// and the backend getDefaultSystemModel() (only matches SYSTEM_MODELS entries;
+// entries without a matching system provider are silently skipped server-side).
+export const PROVIDER_PRIORITY: string[] = [
+  "anthropic",
```
Comment (XinweiHe) [inline frontend/packages/core/src/llm-providers.ts]: not using raw string?

File: frontend/ui/src/features/ai-assistant/components/model-selector.tsx (hunk 4 above)
Comment (shirleyai-co) [reply frontend/ui/src/features/ai-assistant/components/model-selector.tsx]: Replaced the sort-based approach with a simple linear search:

  // Before (hard to read)
  const sorted = [...models].sort((a, b) => {
    const aIdx = PROVIDER_PRIORITY.indexOf(a.provider.toLowerCase());
    const bIdx = PROVIDER_PRIORITY.indexOf(b.provider.toLowerCase());
    return (aIdx === -1 ? 999 : aIdx) - (bIdx === -1 ? 999 : bIdx);
  });

  // After (clear intent)
  for (const adapter of PROVIDER_PRIORITY) {
    const match = models.find((m) => m.provider.toLowerCase() === adapter);
    if (match) {
      onChange({ model: match.id, provider: match.provider, source: match.source });
      break;
    }
  }

File: frontend/packages/core/src/llm-providers.ts (hunk 5 above)
Comment (shirleyai-co) [reply frontend/packages/core/src/llm-providers.ts]: Fixed. Now uses LLMAdapter.ANTHROPIC. instead of raw "anthropic" strings.

**Review by XinweiHe — APPROVED** [review]
LGTM
